# Generated by Django 3.2.8 on 2021-10-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_criado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
