# Generated by Django 3.2.8 on 2021-10-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_criado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
