# Generated by Django 3.2.8 on 2021-10-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_criado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='posicao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='produtos.posicao'),
        ),
    ]
