# Generated by Django 3.2.8 on 2021-10-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='usuario',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
